fix for build issues with tcpclient and samples #34
IBMStreams/streamsx.tcp pull request #35
Opened 2016-09-13 18:11 UTC by crecoskie

2016-09-17 18:59 UTC, leongor commented on com.ibm.streamsx.tcp/toolkit.xml
> +<toolkitModel xmlns="http://www.ibm.com/xmlns/prod/streams/spl/toolkit" productVersion="4.2.0.0" xmlns:common="http://www.ibm.com/xmlns/prod/streams/spl/common" xmlns:ti="http://www.ibm.com/xmlns/pro
productVersion="4.2.0.0" in toolkit.xml better to be changed to 4.0

2016-09-17 19:01 UTC, leongor requested changes
Please, change product version from 4.2 to 4.0 in all toolkit.xml files.

2016-09-19 14:58 UTC, crecoskie commented
I modified the commit as requested.

2016-09-19 15:09 UTC, leongor approved these changes

2016-09-19 15:10 UTC, merged